=== petoadam1/S0KK3C_XMLGyak/XMLTasks0kk3c/DOMParses0kk3c/XMLSchemas0kk3c.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="etterem_service">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="etterem" type="etterem_type"/>
                    <xs:element name="nyersanyag" type="nyersanyag_type"/>
                    <xs:element name="termelo" type="termelo_type"/>
                    <xs:element name="etel" type="etel_type"/>
                    <xs:element name="vendeg" type="vendeg_type"/>
                    <xs:element name="rendeles" type="rendeles_type"/>
                    <xs:element name="rendelo" type="rendelo_type"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
        
        <xs:key name="etteremid_PK">
            <xs:selector xpath="etterem"/>
            <xs:field xpath="@adoszam"/>
        </xs:key>
        <xs:key name="nyeranyagId_PK">
            <xs:selector xpath="nyersanyag"/>
            <xs:field xpath="@azonosito"/>
        </xs:key>
        <xs:key name="termeloId_PK">
            <xs:selector xpath="termelo"/>
            <xs:field xpath="@tid"/>
        </xs:key>
        <xs:key name="etelId_PK">
            <xs:selector xpath="etel"/>
            <xs:field xpath="@etelkod"/>
        </xs:key>
        <xs:key name="vendegId_PK">
            <xs:selector xpath="vendeg"/>
            <xs:field xpath="@vendegkod"/>
        </xs:key>
        <xs:key name="rendelesId_PK">
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="@rszam"/>
        </xs:key>
        <xs:key name="rendeloId_PK">
            <xs:selector xpath="rendelo"/>
            <xs:field xpath="@vevokod"/>
        </xs:key>
        <xs:keyref name="etelId_FK" refer="etelId_PK">
            <xs:selector xpath="etterem"/>
            <xs:field xpath="@etelId"/>
        </xs:keyref>
        <xs:keyref name="nyeranyagId_FK" refer="nyeranyagId_PK">
            <xs:selector xpath="etterem"/>
            <xs:field xpath="@nyersanyagId"/>
        </xs:keyref>
        <xs:keyref name="termeloId_FK" refer="termeloId_PK">
            <xs:selector xpath="nyersanyag"/>
            <xs:field xpath="@termeloId"/>
        </xs:keyref>
        <xs:keyref name="vendegId_FK" refer="vendegId_PK">
            <xs:selector xpath="etel"/>
            <xs:field xpath="@vendegId"/>
        </xs:keyref>
        <xs:keyref name="rendelesId_FK" refer="rendelesId_PK">
            <xs:selector xpath="etel"/>
            <xs:field xpath="@rendelesId"/>
        </xs:keyref>
        <xs:keyref name="rendeloId_FK" refer="rendeloId_PK">
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="@rendeloId"/>
        </xs:keyref>
    </xs:element>
    
     <xs:complexType name="etterem_type">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="elerhetoseg" type="elerhetoseg_type"/>
            <xs:element name="cim" type="cim_type"/>
        </xs:sequence>
        <xs:attribute name="adoszam" type="xs:unsignedByte" use="required"/>
        <xs:attribute name="etelId" type="xs:unsignedByte" use="required"/>
        <xs:attribute name="nyersanyagId" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    <xs:complexType name="nyersanyag_type">
        <xs:sequence>
            <xs:element name="tipus" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="azonosito" type="xs:unsignedByte" use="required"/>
        <xs:attribute name="termeloId" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    <xs:complexType name="termelo_type">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="telephely" type="cim_type"/>
        </xs:sequence>
        <xs:attribute name="tid" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    <xs:complexType name="etel_type">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="etelkod" type="xs:unsignedByte" use="required"/>
        <xs:attribute name="vendegId" type="xs:unsignedByte" use="required"/>
        <xs:attribute name="rendelesId" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    <xs:complexType name="vendeg_type">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="eletkor" type="xs:integer"/>
            <xs:element name="nem" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="vendegkod" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    <xs:complexType name="rendeles_type">
        <xs:sequence>
            <xs:element name="datum" type="datum_type"/>
        </xs:sequence>
        <xs:attribute name="rszam" type="xs:unsignedByte" use="required"/>
        <xs:attribute name="rendeloId" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    <xs:complexType name="rendelo_type">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="lakcim" type="cim_type"/>
        </xs:sequence>
        <xs:attribute name="vevokod" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    <xs:complexType name="elerhetoseg_type">
        <xs:sequence>
            <xs:element name="telefonszam" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="cim_type">
        <xs:sequence>
            <xs:element name="iranyitoszam" type="xs:string"/>
            <xs:element name="varos" type="xs:string"/>
            <xs:element name="utca" type="xs:string"/>
            <xs:element name="hazszam" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

	<xs:simpleType name="datum_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{4}\.(0[1-9]|1[012])\.(0[1-9]|[12][0-9]|3[01])"/> <!-- YYYY.MM.DD -->
        </xs:restriction>
    </xs:simpleType>
	<xs:simpleType name="telefonszam_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}-\d{3}-\d{4}"/>
            <xs:pattern value="\d{2}-\d{3}-\d{3}"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== petoadam1/S0KK3C_XMLGyak/XMLTasks0kk3c/DOMParses0kk3c/XMLs0kk3c.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><etterem_service xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemas0kk3c.xsd">

	<etterem adoszam="00001" etelId="101" nyersanyagId="001">
		<nev>Csülök Bisztró</nev>
		<elerhetoseg>
			<telefonszam>+30-123-4567</telefonszam>
			<email>csulokbusz@gmail.com</email>
		</elerhetoseg>
		<cim>
			<iranyitoszam>3000</iranyitoszam>
			<varos>Miskolc</varos>
			<utca>Futó utca</utca>
			<hazszam>25</hazszam>
		</cim>
	</etterem>
	<etterem adoszam="00002" etelId="102" nyersanyagId="002">
		<nev>Végállomás Bisztró</nev>
		<elerhetoseg>
			<telefonszam>+30-987-6543</telefonszam>
			<email>vegallomas@gmail.com</email>
		</elerhetoseg>
		<cim>
			<iranyitoszam>3501</iranyitoszam>
			<varos>Miskolc</varos>
			<utca>Széchenyi István utca</utca>
			<hazszam>107</hazszam>
		</cim>
	</etterem>
	<etterem adoszam="00003" etelId="103" nyersanyagId="003">
		<nev>Pető Hambizó</nev>
		<elerhetoseg>
			<telefonszam>30-456-7981</telefonszam>
			<email>petohambi@gmail.com</email>
		</elerhetoseg>
		<cim>
			<iranyitoszam>3525</iranyitoszam>
			<varos>Budapest</varos>
			<utca>Zsedényi József utca</utca>
			<hazszam>1</hazszam>
		</cim>
	</etterem>
	<nyersanyag azonosito="001" termeloId="0001">
		<tipus>kacsahús</tipus>
	</nyersanyag>
	<nyersanyag azonosito="002" termeloId="0002">
		<tipus>borjúhús</tipus>
	</nyersanyag>
	<nyersanyag azonosito="003" termeloId="0001">
		<tipus>Krumpli</tipus>
	</nyersanyag>
	<nyersanyag azonosito="004" termeloId="0002">
		<tipus>Répa</tipus>
	</nyersanyag>
	<nyersanyag azonosito="005" termeloId="0001">
		<tipus>Liszt</tipus>
	</nyersanyag>
	<termelo tid="0001">
		<nev>Hús Nagyker</nev>
		<telephely>
			<iranyitoszam>3525</iranyitoszam>
			<varos>Budapest</varos>
			<utca>Zsedényi József utca</utca>
			<hazszam>95</hazszam>
		</telephely>
	</termelo>
	<termelo tid="0002">
		<nev>Zöldség, Gyümölcs Nagyker</nev>
		<telephely>
			<iranyitoszam>3520</iranyitoszam>
			<varos>Győr</varos>
			<utca>Berzsenyi Dániel utca</utca>
			<hazszam>8</hazszam>
		</telephely>
	</termelo>
	<etel etelkod="101" rendelesId="000000001" vendegId="01">
		<nev>Sushi</nev>
	</etel>
	<etel etelkod="102" rendelesId="000000002" vendegId="02">
		<nev>Csokis palacsinta</nev>
	</etel>
	<etel etelkod="103" rendelesId="000000001" vendegId="03">
		<nev>Cigány pecsenye</nev>
	</etel>
	<etel etelkod="104" rendelesId="000000003" vendegId="02">
		<nev>Paprikás krumpli</nev>
	</etel>
	<etel etelkod="105" rendelesId="000000002" vendegId="01">
		<nev>Pho leves</nev>
	</etel>
	<vendeg vendegkod="01">
		<nev>Pető Ádám</nev>
		<eletkor>20</eletkor>
		<nem>Férfi</nem>
	</vendeg>
	<vendeg vendegkod="02">
		<nev>Iványi Fruzsina</nev>
		<eletkor>21</eletkor>
		<nem>Nő</nem>
	</vendeg>
	<vendeg vendegkod="03">
		<nev>Szalai Márton</nev>
		<eletkor>21</eletkor>
		<nem>Férfi</nem>
	</vendeg>
	<rendeles rendeloId="001" rszam="000000001">
		<datum>2021.11.15</datum>
	</rendeles>
	<rendeles rendeloId="002" rszam="000000002">
		<datum>2021.11.16</datum>
	</rendeles>
	<rendeles rendeloId="002" rszam="000000003">
		<datum>2021.11.17</datum>
	</rendeles>
	<rendelo vevokod="001">
		<nev>Pető Ádám</nev>
		<lakcim>
			<iranyitoszam>3525</iranyitoszam>
			<varos>Szeged</varos>
			<utca>Berzsenyi Dániel utca</utca>
			<hazszam>9</hazszam>
		</lakcim>
	</rendelo>
	<rendelo vevokod="002">
		<nev>Sebák Petra</nev>
		<lakcim>
			<iranyitoszam>3522</iranyitoszam>
			<varos>Gesztely</varos>
			<utca>Aba utca</utca>
			<hazszam>15</hazszam>
		</lakcim>
	</rendelo>
</etterem_service>
